In [6]:
heights = [189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185, 191]

In [7]:
import numpy as np
heights_arr =  np.array(heights)

In [8]:
ages = [57, 61, 57, 57, 58, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70]

In [9]:
ages_arr =  np.array(ages)

In [11]:
heights_arr =  heights_arr.reshape((45,1))
ages_arr =  ages_arr.reshape((45,1))
height_age_arr = np.hstack((heights_arr, ages_arr))
height_age_arr.shape

(45, 2)

In [16]:
print(height_age_arr)

[[189  57]
 [170  61]
 [189  57]
 [163  57]
 [183  58]
 [171  57]
 [185  61]
 [168  54]
 [173  68]
 [183  51]
 [173  49]
 [173  64]
 [175  50]
 [178  48]
 [183  65]
 [193  52]
 [178  56]
 [173  46]
 [174  54]
 [183  49]
 [183  51]
 [180  47]
 [168  55]
 [180  55]
 [170  54]
 [178  42]
 [182  51]
 [180  56]
 [183  55]
 [178  51]
 [182  54]
 [188  51]
 [175  60]
 [179  62]
 [183  43]
 [193  55]
 [182  56]
 [183  61]
 [177  52]
 [185  69]
 [188  64]
 [188  46]
 [182  54]
 [185  47]
 [191  70]]


In [17]:
height_age_arr[:3,]

array([[189,  57],
       [170,  61],
       [189,  57]])

In [18]:
heights_arr =  heights_arr.reshape((1,45))
ages_arr =  ages_arr.reshape((1,45))
height_age_arr = np.vstack((heights_arr, ages_arr))
height_age_arr.shape

(2, 45)

In [20]:
print(height_age_arr)

[[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
  174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
  182 183 177 185 188 188 182 185 191]
 [ 57  61  57  57  58  57  61  54  68  51  49  64  50  48  65  52  56  46
   54  49  51  47  55  55  54  42  51  56  55  51  54  51  60  62  43  55
   56  61  52  69  64  46  54  47  70]]


In [19]:
height_age_arr[:,:3]

array([[189, 170, 189],
       [ 57,  61,  57]])

In [30]:
height_age_arr = np.concatenate((heights_arr, ages_arr), axis=1)

In [31]:
print(height_age_arr)

[[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
  174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
  182 183 177 185 188 188 182 185 191  57  61  57  57  58  57  61  54  68
   51  49  64  50  48  65  52  56  46  54  49  51  47  55  55  54  42  51
   56  55  51  54  51  60  62  43  55  56  61  52  69  64  46  54  47  70]]


In [32]:
height_age_arr[:,0]*0.0328084

array([6.2007876])

In [ ]:
#You can use np.hstack to concatenate arrays ONLY if they have the same number of rows.

In [27]:
height_age_arr = np.concatenate((heights_arr, ages_arr), axis=0)

In [28]:
print(height_age_arr )

[[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
  174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
  182 183 177 185 188 188 182 185 191]
 [ 57  61  57  57  58  57  61  54  68  51  49  64  50  48  65  52  56  46
   54  49  51  47  55  55  54  42  51  56  55  51  54  51  60  62  43  55
   56  61  52  69  64  46  54  47  70]]


In [ ]:
##
Performing mathematical operations on arrays is straightforward. For instance, to convert the heights from centimeters to feet, knowing that 1 centimeter is equal to 0.0328084 feet, we can use multiplication:

In [39]:
height_age_arr[:,0]*0.0328084

array([6.2007876])

In [46]:
heights_arr =  heights_arr.reshape((45,1))
ages_arr =  ages_arr.reshape((45,1))
height_age_arr = np.hstack((heights_arr, ages_arr))
height_age_arr.shape

(45, 2)

mask  = height_age_arr[:,0] >= 182

In [47]:
mask = height_age_arr[:,0] >= 182
mask.sum()

23

In [48]:
tall_pre =  height_age_arr[mask,]

In [49]:
tall_pre.shape

(23, 2)

In [50]:
print(tall_pre)

[[189  57]
 [189  57]
 [183  58]
 [185  61]
 [183  51]
 [183  65]
 [193  52]
 [183  49]
 [183  51]
 [182  51]
 [183  55]
 [182  54]
 [188  51]
 [183  43]
 [193  55]
 [182  56]
 [183  61]
 [185  69]
 [188  64]
 [188  46]
 [182  54]
 [185  47]
 [191  70]]


In [51]:
mask = (height_age_arr[:,0] >= 182) & ( height_age_arr[:,1] <= 50)

In [52]:
height_age_arr[mask,]

array([[183,  49],
       [183,  43],
       [188,  46],
       [185,  47]])